version: '3'
services:
  # Zipkin
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    ports:
      - '9411:9411'

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector:0.50.0
    command: ['--config=/etc/otel-collector-config.yaml']
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - '4318:4318'
    depends_on:
      - zipkin-all-in-one

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - '3000:3000'

  server:
    container_name: dem-heights-container
    build: .
    ports:
      - 8000:8000
    network_mode: host
    environment:
      TERRAIN_PROVIDERS_TOKEN: eyJhbGciOiJSUzI1NiIsImtpZCI6Im1hcC1jb2xvbmllcy1pbnQifQ.eyJhbyI6WyJodHRwczovL2FwcC1pbnQtY2xpZW50LXJvdXRlLWludGVncmF0aW9uLmFwcHMuajFsazNuanAuZWFzdHVzLmFyb2FwcC5pbyIsImh0dHBzOi8vYXBwLWludC1jbGllbnQtdG9vbHMtcm91dGUtaW50ZWdyYXRpb24uYXBwcy5qMWxrM25qcC5lYXN0dXMuYXJvYXBwLmlvIiwiaHR0cDovL2xvY2FsaG9zdDozMDAwIl0sImQiOlsicmFzdGVyIiwicmFzdGVyV21zIiwicmFzdGVyRXhwb3J0IiwiZGVtIiwidmVjdG9yIiwiM2QiXSwiaWF0IjoxNjc0NjMyMzQ2LCJzdWIiOiJtYXBjb2xvbmllcy1hcHAiLCJpc3MiOiJtYXBjb2xvbmllcy10b2tlbi1jbGkifQ.e-4SmHNOE8FwpcJoHdp-3Dh6D8GqCwM5wZfZIPrivGhfeKdihcsjEj_WN2jWN-ULha_ytZN5gRusLjwikNwgbF6hvb-QTDe3bEHPAjtgpZmF4HaJze8e6VPDF1tTC52CHDzNnwkUGAH1tnVGq10SnyhsGDezUChTVeBeVu-swTI58qCjemUQRw7-Q03uSEH24AkbX2CC1_rNwulo7ChglyTdn01tTWPsPjIuDjeixxm2CUmUHpfZzroaSzwof7ByQe22o3tFddje6ItNLBUC_VN7UfNLa_QPSVbIuNac-iMGFbK-RIyXUK8mp1AwddvSGsBUYcDs8fWMLzKhItljnw
      DEM_CATALOG_RECORDS: '[{ "__typename": "LayerDemRecord", "id": "22111111-1111-1111-1111-111111111111", "type": "RECORD_DEM", "classification": "5", "productName": "combined_srtm_30_100_il_ever", "description": null, "srsId": "EPSG:4326", "srsName": "WGS84GEO", "producerName": "IDFMU", "updateDate": "2023-05-08T17:44:01.000Z", "sourceDateStart": "2023-04-21T00:00:00.000Z", "sourceDateEnd": "2023-04-21T00:00:00.000Z", "sensors": [ "UNDEFINED" ], "region": [ "Israel" ], "productId": "22111111-1111-1111-1111-111111111111", "productType": "QUANTIZED_MESH_DTM_BEST", "footprint": { "coordinates": [ [ [ [ 34.948657607318694, 33.005610036521034 ], [ 34.948657607318694, 30.99294299883441 ], [ 35.71215014987706, 30.99294299883441 ], [ 35.71215014987706, 33.005610036521034 ], [ 34.948657607318694, 33.005610036521034 ] ] ], [ [ [ 85.00067953671106, 29.41200402481249 ], [ 85.00067953671106, 25.577400008336326 ], [ 89.32770820921479, 25.577400008336326 ], [ 89.32770820921479, 29.41200402481249 ], [ 85.00067953671106, 29.41200402481249 ] ] ] ], "type": "MultiPolygon" }, "absoluteAccuracyLEP90": 9e-7, "relativeAccuracyLEP90": 9e-7, "resolutionDegree": 0.00833, "resolutionMeter": 30, "imagingSortieAccuracyCEP90": 30, "layerPolygonParts": null, "productBoundingBox": null, "heightRangeFrom": -500, "heightRangeTo": 9000, "geographicArea": "Israel Nepal", "undulationModel": "ILUM", "dataType": "INT16", "noDataValue": "NO_DATA_999", "productStatus": "PUBLISHED", "hasTerrain": true, "insertDate": "2023-04-21T00:00:00.000Z", "wktGeometry": null, "keywords": "Israel Nepal, terrain, EPSG:4326", "links": [ { "__typename": "Link", "name": "", "description": "", "protocol": "TERRAIN_QMESH", "url": "https://dem-int-nginx-s3-gateway-production-route-integration.apps.j1lk3njp.eastus.aroapp.io/api/dem/v1/terrains/combined_srtm_30_100_il_ever" } ] },{ "__typename": "LayerDemRecord", "id": "11111111-1111-1111-1111-111111111111", "type": "RECORD_DEM", "classification": "5", "productName": "srtm100", "description": null, "srsId": "EPSG:4326", "srsName": "WGS84GEO", "producerName": "IDFMU", "updateDate": "2023-04-21T23:44:41.000Z", "sourceDateStart": "2023-04-21T00:00:00.000Z", "sourceDateEnd": "2023-04-21T00:00:00.000Z", "sensors": [ "UNDEFINED" ], "region": [ "Israel" ], "productId": "11111111-1111-1111-1111-111111111111", "productType": "QUANTIZED_MESH_DTM_BEST", "footprint": { "type": "Polygon", "coordinates": [ [ [ 34.999861111, 31.999861111 ], [ 34.999861111, 33.000138889 ], [ 36.000138889, 33.000138889 ], [ 36.000138889, 31.999861111 ], [ 34.999861111, 31.999861111 ] ] ] }, "absoluteAccuracyLEP90": 9e-7, "relativeAccuracyLEP90": 9e-7, "resolutionDegree": 0.00833, "resolutionMeter": 100, "imagingSortieAccuracyCEP90": 30, "layerPolygonParts": null, "productBoundingBox": null, "heightRangeFrom": -500, "heightRangeTo": 9000, "geographicArea": "North", "undulationModel": "ILUM", "dataType": "INT16", "noDataValue": "NO_DATA_999", "productStatus": "PUBLISHED", "hasTerrain": true, "insertDate": "2023-04-21T00:00:00.000Z", "wktGeometry": null, "keywords": "North, terrain, EPSG:4326", "links": [ { "__typename": "Link", "name": "", "description": "", "protocol": "TERRAIN_QMESH", "url": "https://dem-int-nginx-s3-gateway-production-route-integration.apps.j1lk3njp.eastus.aroapp.io/api/dem/v1/terrains/srtm100" } ] }]'
      PROTO_FILE_URL: https://github.com/MapColonies/dem-heights-data.git
      SERVICE_VERSION: v2
      MAXIMUM_TILES_PER_REQUEST: 250
      TELEMETRY_TRACING_ENABLED: 'true'
      TELEMETRY_TRACING_URL: http://otel-collector:4318/v1/traces
      TELEMETRY_METRICS_ENABLED: 'true'
      TELEMETRY_METRICS_URL: http://otel-collector:4318/v1/metrics
