version: '3'
services:
  # Zipkin
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    ports:
      - 9411:9411
    network_mode: host
  # Collector
  otel-collector:
    image: otel/opentelemetry-collector:0.50.0
    command: ['--config=/etc/otel-collector-config.yaml']
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 55670:55679 # zpages extension
      - 8887:8888 # Prometheus metrics exposed by the agent
      - 4317:4317 # OTLP gRPC receiver
      - 9411 # Zipkin receiver
      - 1777:1777 # pprof extension
      - 55679:55679 # zpages extension
      - 13133 # health_check      - "8887:8888"   # Prometheus metrics exposed by the agent
      - 14250 # Jaeger grpc receiver
      - 14268 # Jaeger http thrift receiver
      - 55678 # OpenCensus receiver
      - 55681:55681
      - 4318:4318
    network_mode: host
    depends_on:
      - zipkin-all-in-one
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    network_mode: host
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    network_mode: host
