openapi: 3.0.1
info:
  title: dem-heights
  description: map-colonies service for extracting elevations from DTM/DSM geotiffs
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

paths:
  /heights/points:
    post:
      operationId: pointsHeight
      tags:
        - heights
      summary: get points heights
      requestBody:
        description: Points to calculate heights for.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/pointsReq'
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pointsRes'
            application/octet-stream:
              schema:
                type: string
                format: binary
        500: 
          description: Service Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        400:
          description: Points density is too low to compute
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
  /heights/helpers/generateProtoBinary:
    post:
      operationId: generateProtoBinary
      tags:
        - heights
      summary: Generate protobuffed binary for a json request
      requestBody:
        description: JSON request to parse
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/pointsReq'
      responses:
        200:
          description: OK
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
  /heights/helpers/generateJsonPoints:
    get:
      operationId: generateJsonPoints
      tags:
        - heights
      summary: Generate points request by a coordinate
      parameters:
        - name: coordinate
          in: query
          description: Coordinate to generate points in it's area.
          required: true
          schema:
            type: string
            example: "27.988257 86.925145 Latitude Longitude - Coordinate somewhere on everest (Space separated)"
        - name: pointsCount
          in: query
          description: Number of points to generate.
          required: false
          schema:
            type: integer
            minimum: 100
            example: 10000
            default: 10000
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pointsReq'
components:
  schemas:
    error:
      type: object
      required:
        - message
        - errorCode
      properties:
        message:
          type: string
        errorCode:
          oneOf:
            - $ref: '#/components/schemas/errorCodesEnum'
    pointsReq:
      type: object
      required:
        - positions
      properties:
        positions:
          type: array
          items:
            type: object
            required:
              - longitude
              - latitude
            properties:
              longitude:
                type: number
                format: double
              latitude:
                type: number
                format: double
        productType:
          oneOf:
            - $ref: '#/components/schemas/productTypeEnum'
          default: MIXED
        excludeFields:
          type: array
          uniqueItems: true
          items:
            oneOf: 
              - $ref: '#/components/schemas/excludeFieldsEnum'
          
    pointsRes:
      type: object
      required:
        - data
      properties:
        data:
          type: array
          items:
            type: object
            required:
              - longitude
              - latitude
              - height
            properties:
              longitude:
                type: number
                format: double
              latitude:
                type: number
                format: double
              height:
                nullable: true
                type: number
                format: double
    productTypeEnum:
      type: string
      enum: 
        - DSM
        - DTM
        - MIXED
    excludeFieldsEnum:
      type: string
      enum:
        - productType
        - updateDate
        - resolutionMeter
    errorCodesEnum:
      type: string
      enum:
        - POINTS_DENSITY_TOO_LOW_ERROR
        - GENERAL_SERVER_ERROR
