openapi: 3.0.1
info:
  title: dem-elevation-extractor
  description: map colonies service for extracting elevations from DTM/DSM geotiffs
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

paths:
  /heights/{longitude}/{latitude}:
    get:
      operationId: getHeights
      tags:
        - heights
      summary: get heights
      parameters:
        - name: longitude
          in: path
          required: true
          schema:
            type: number
          example: 35.034
        - name: latitude
          in: path
          required: true
          schema:
            type: number
          example: 32.691
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/heights'
  /heights:
    post:
      operationId: getHeightsList
      tags:
        - heights
      summary: get heights
      requestBody:
        content:
          application/json:
              schema:
                type: object
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
components:
  schemas:
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    heights:
      type: object
      required:
        - dem
      properties:
        dem:
          type: number
          format: int64
