global:
  scrape_interval: 10s

scrape_configs:
  - job_name: otel-collector
    static_configs:
      - targets: ['otel-collector:8889']
      - targets: ['otel-collector:8888']
  - job_name: server
    static_configs:
      - targets: ['server:8000/metrics']