scrape_configs:
  - job_name: otel-collector
    static_configs:
      - targets: [otel-collector:8889]
      - targets: [otel-collector:8888]
  - job_name: server
    scrape_interval: 10s
    static_configs:
      - targets: [localhost:8000]
