{{- $MAIN_OBJECT_BLOCK := "configValues" -}}
{{- $COMPONENT_NAME := "backend" -}}

{{- define "confMapData" -}}
{{- $tracingEnabled := include "heights.tracingEnabled" . -}}
{{- $tracingUrl := include "heights.tracingUrl" . -}}
{{- $metricsEnabled := include "heights.metricsEnabled" . -}}
{{- $metricsUrl := include "heights.metricsUrl" . -}}
  production.json: {{ .Files.Get "config/production.json" | quote }}
  ACCESS_TOKEN_ATTRIBUTE_NAME: {{ .Values.accessToken.attributeName | quote }}
  ACCESS_TOKEN_INJECTION_TYPE: {{ .Values.accessToken.injectionType | quote }}
  ACCESS_TOKEN_TOKEN_VALUE: {{ .Values.accessToken.tokenValue | quote }}
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if .Values.env.tracing.enabled -}}
  TELEMETRY_TRACING_ENABLED: {{ $tracingEnabled | quote }}
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end -}}
  {{ if .Values.env.metrics.enabled -}}
  TELEMETRY_METRICS_ENABLED: {{ $metricsEnabled | quote }}
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  TELEMETRY_METRICS_BUCKETS: {{ .Values.env.metrics.buckets | toJson | quote }}
  {{ end -}}
  CSW_DEM_URL: {{ .Values.env.cswDemUrl | quote }}
  S3_GATEWAY_DEM_URL: {{ .Values.env.s3GatewayDemUrl | quote }}
  SYNCH_RECORDS_INTERVAL: {{ .Values.env.synchRecordsInterval | quote }}
  PROTO_FILE_URL: {{ .Values.env.protoFileUrl | quote }}
  SERVICE_VERSION: {{ .Values.env.serviceVersion | quote }}
  MAXIMUM_TILES_PER_REQUEST: {{ .Values.env.maximumTilesPerRequest | quote }}
  # BUKU: {{ dig "serving" "heights" "overrideGlobal" "logLevel" "GGGGGG" .Values.global }}
  KUKU: {{ include "common.tplvalues.getGlobalValue" (dict "propName" "testGlobalVal" "context" .) | quote}}
{{- end -}}

{{- $DATA := include "confMapData" . -}}
{{ include "mc-chart.configmap" (dict "MAIN_OBJECT_BLOCK" $MAIN_OBJECT_BLOCK "COMPONENT_NAME" $COMPONENT_NAME "DATA" $DATA "context" .) }}

{{/*
{{- if .Values.enabled -}}
{{- $releaseName := .Release.Name -}}
{{- $chartName := include "heights.name" . -}}
{{- $tracingEnabled := include "heights.tracingEnabled" . -}}
{{- $tracingUrl := include "heights.tracingUrl" . -}}
{{- $metricsEnabled := include "heights.metricsEnabled" . -}}
{{- $metricsUrl := include "heights.metricsUrl" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $releaseName }}-{{ $chartName }}-configmap
data:
  production.json: {{ .Files.Get "config/production.json" | quote }}
  ACCESS_TOKEN_ATTRIBUTE_NAME: {{ .Values.accessToken.attributeName | quote }}
  ACCESS_TOKEN_INJECTION_TYPE: {{ .Values.accessToken.injectionType | quote }}
  ACCESS_TOKEN_TOKEN_VALUE: {{ .Values.accessToken.tokenValue | quote }}
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if .Values.env.tracing.enabled -}}
  TELEMETRY_TRACING_ENABLED: {{ $tracingEnabled | quote }}
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end -}}
  {{ if .Values.env.metrics.enabled -}}
  TELEMETRY_METRICS_ENABLED: {{ $metricsEnabled | quote }}
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  TELEMETRY_METRICS_BUCKETS: {{ .Values.env.metrics.buckets | toJson | quote }}
  {{ end -}}
  CSW_DEM_URL: {{ .Values.env.cswDemUrl | quote }}
  S3_GATEWAY_DEM_URL: {{ .Values.env.s3GatewayDemUrl | quote }}
  SYNCH_RECORDS_INTERVAL: {{ .Values.env.synchRecordsInterval | quote }}
  PROTO_FILE_URL: {{ .Values.env.protoFileUrl | quote }}
  SERVICE_VERSION: {{ .Values.env.serviceVersion | quote }}
  MAXIMUM_TILES_PER_REQUEST: {{ .Values.env.maximumTilesPerRequest | quote }}
{{- end }}
*/}}