{{- $chartName := include "heights.name" . -}}
{{- $tracingUrl := include "heights.tracingUrl" . -}}
{{- $metricsUrl := include "heights.metricsUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-configmap
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
  TERRAIN_PROVIDERS_TOKEN: {{ .Values.env.terrainProvidersToken | quote }}
  DEM_CATALOG_RECORDS: {{ .Values.env.demCatalogRecords | quote }}
  PROTO_FILE_URL: {{ .Values.env.protoFileUrl | quote }}
  SERVICE_VERSION: {{ .Values.env.serviceVersion | quote }}
  MAXIMUM_TILES_PER_REQUEST: {{ .Values.env.maximumTilesPerRequest }}
{{- end }}
