{{- if .Values.enabled -}}
{{- $tracingEnabled := include "heights.tracingEnabled" . -}}
{{- $tracingUrl := include "heights.tracingUrl" . -}}
{{- $metricsEnabled := include "heights.metricsEnabled" . -}}
{{- $metricsUrl := include "heights.metricsUrl" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: {{ $tracingEnabled | quote }}
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: {{ $metricsEnabled | quote }}
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  TELEMETRY_METRICS_BUCKETS: {{ .Values.env.metrics.buckets | toJson | quote }}
  {{ end }}
  ACCESS_TOKEN_ATTRIBUTE_NAME: {{ .Values.env.accessToken.attributeName | quote }}
  ACCESS_TOKEN_INJECTION_TYPE: {{ .Values.env.accessToken.injectionType | quote }}
  ACCESS_TOKEN_TOKEN_VALUE: {{ .Values.env.accessToken.tokenValue | quote }}
  CSW_DEM_URL: {{ .Values.env.cswDemUrl | quote }}
  S3_GATEWAY_DEM_URL: {{ .Values.env.s3GatewayDemUrl | quote }}
  SYNCH_RECORDS_INTERVAL: {{ .Values.env.synchRecordsInterval }}
  PROTO_FILE_URL: {{ .Values.env.protoFileUrl | quote }}
  SERVICE_VERSION: {{ .Values.env.serviceVersion | quote }}
  MAXIMUM_TILES_PER_REQUEST: {{ .Values.env.maximumTilesPerRequest }}
{{- end }}
