{{- if .Values.nginx.enabled -}}
{{- $releaseName := .Release.Name -}}
{{- $chartName := include "heights.name" . -}}
{{- $serviceName := include "service.fullname" . -}}
{{- $cloudProviderFlavor := include "heights.cloudProviderFlavor" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}-nginx
  labels:
    app: {{ $releaseName }}-{{ $chartName }}
    component: nginx-service
    environment: {{ include "heights.environment" . }}
    release: {{ $releaseName }}
    # {{- include "heights.labels" . | nindent 4 }}
spec:
  # In case cloudProavider=azure
  {{- if eq $cloudProviderFlavor "azure" }}
  type: ClusterIP
  {{- end }}
  # In case cloudProvider=minikube
  {{- if eq $cloudProviderFlavor "minikube" }}
  type: NodePort
  {{- end }}
  ports:
    - name: internal
      port: {{ .Values.nginx.internalPort }}
      targetPort: {{ .Values.env.port }}
      protocol: {{ .Values.env.protocol }}
    {{- if .Values.authentication.opa.enabled }}
    - name: external
      port: {{ .Values.nginx.port }}
      targetPort: {{ .Values.envoy.port }}
      protocol: {{ .Values.env.protocol }}
    {{- end }}
    {{- if eq $cloudProviderFlavor "minikube" }}
    nodePort: {{ .Values.nginx.nodePort }}
    {{- end }}
  selector:
    app: {{ $releaseName }}-{{ $chartName }}
    release: {{ $releaseName }}
    run: {{ $releaseName }}-nginx
    # {{- include "heights.selectorLabels" . | nindent 4 }}
{{- end }}
