{{- if .Values.enabled -}}
{{- $releaseName := .Release.Name -}}
{{- $chartName := include "heights.name" . -}}
{{- $cloudProviderFlavor := include "heights.cloudProviderFlavor" . -}}
{{ $targetPort := ternary .Values.envoy.port .Values.env.targetPort .Values.authentication.opa.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $releaseName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "heights.environment" . }}
    release: {{ $releaseName }}
    {{- include "heights.labels" . | nindent 4 }}
spec:
  {{- if eq $cloudProviderFlavor "minikube" }}
  type: NodePort
  {{- end }}
  ports:
    - port: {{ .Values.env.port }}
      targetPort: {{ $targetPort }}
      protocol: {{ .Values.env.protocol }}
      name: external
      {{- if eq $cloudProviderFlavor "minikube" }}
      nodePort: {{ .Values.nodePort }}
      {{- end }}
    {{- if .Values.authentication.opa.enabled }}
    - port: {{ .Values.env.internalPort }}
      targetPort: {{ .Values.env.targetPort }}
      protocol: TCP
      name: internal
    {{- end }}
  selector:
    app: {{ $chartName }}
    release: {{ $releaseName }}
    run: {{ $releaseName }}-{{ $chartName }}
    {{- include "heights.selectorLabels" . | nindent 4 }}
{{- end }}
