
{{- $MAIN_OBJECT_BLOCK := "configValues" -}}
{{- $COMPONENT_NAME := "backend" -}}
{{ include "mc-chart.service" (dict "MAIN_OBJECT_BLOCK" $MAIN_OBJECT_BLOCK "COMPONENT_NAME" $COMPONENT_NAME "context" .) }}

{{/*
{{- if .Values.enabled -}}
{{- $releaseName := .Release.Name -}}
{{- $chartName := include "heights.name" . -}}
{{- $serviceName := include "service.fullname" . -}}
{{- $cloudProviderFlavor := include "heights.cloudProviderFlavor" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "heights.environment" . }}
    release: {{ $releaseName }}
    {{- include "heights.labels" . | nindent 4 }}
spec:
  {{- if eq $cloudProviderFlavor "minikube" }}
  type: NodePort
  {{- end }}
  ports:
    - port: {{ .Values.env.port }}
      targetPort: {{ .Values.env.targetPort }}
      protocol: {{ .Values.env.protocol }}
      {{- if eq $cloudProviderFlavor "minikube" }}
      nodePort: {{ .Values.nodePort }}
      {{- end }}
  selector:
    app: {{ $chartName }}
    release: {{ $releaseName }}
    run: {{ $releaseName }}-{{ $chartName }}
    {{- include "heights.selectorLabels" . | nindent 4 }}
{{- end }}
*/}}