{
 "title": "DEM - elevations",
 "tags": [
  "dem-heights",
  "node.js"
 ],
 "time": { "from": "2023-08-24T13:46:19.313Z", "to": "2023-10-23T13:46:19.313Z" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,15m,30m,1h,6h,12h,24h"
   },
   { "name": "namespace", "label": "Namespace", "query": "integration,dem-dev" },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(http_request_duration_seconds_count{namespace=\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$pod - heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "repeat": "pod",
   "targets": [
    {
     "expr": "rate(elevations_requests_total{service_name=\"dem-heights\", namespace=\"$namespace\", pod=\"$pod\"}[$interval])",
     "legendFormat": "{{points_number}} points"
    }
   ]
  },
  {
   "title": "$pod - counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "repeat": "pod",
   "targets": [
    {
     "expr": "rate(elevations_requests_total{service_name=\"dem-heights\", pod=\"$pod\"}[$interval])",
     "legendFormat": "{{points_number}} points"
    }
   ]
  },
  {
   "title": "$namespace - summary",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "elevations_requests_total{service_name=\"dem-heights\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}} {{points_number}} points"
    }
   ]
  },
  {
   "title": "$pod - duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "repeat": "pod",
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_request_duration_seconds_bucket{service_name=\"dem-heights\", pod=~\"$pod\"}[$interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(http_request_duration_seconds_bucket{service_name=\"dem-heights\", pod=~\"$pod\"}[$interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{service_name=\"dem-heights\", pod=~\"$pod\"}[$interval])) / sum(rate(http_request_duration_seconds_count{service_name=\"dem-heights\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "$namespace - duration stats (seconds)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_request_duration_seconds_bucket{service_name=\"dem-heights\", pod=~\"$pod\"}[$interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(http_request_duration_seconds_bucket{service_name=\"dem-heights\", pod=~\"$pod\"}[$interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{service_name=\"dem-heights\", pod=~\"$pod\"}[$interval])) / sum(rate(http_request_duration_seconds_count{service_name=\"dem-heights\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Current",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elevations_current_requests_count{service_name=\"dem-heights\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Up",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{service_name=\"dem-heights\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}