apiVersion: v2
name: dem-heights
description: Helm chart for heights service
type: application
version: 3.0.4
appVersion: 3.0.4
dependencies:
  - name: nginx
    version: 2.5.0
    repository: oci://acrarolibotnonprod.azurecr.io/helm/common
