apiVersion: v2
name: dem-heights
description: Helm chart for heights service
type: application
version: 2.1.7
appVersion: 2.1.7
dependencies:
  - name: nginx
    version: 2.1.0
    repository: oci://acrarolibotnonprod.azurecr.io/helm/common
