global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: {}

enabled: true
environment: development
replicaCount: 1
initialDelaySeconds: 60
nodePort: 30030 #for minikube deployment only
resetOnConfigChange: true
imagePullPolicy: Always
splunkIndex: ''

cloudProvider:
  dockerRegistryUrl: my-registry-url.io
  imagePullSecretName: my-registry-secret
  flavor: openshift

caSecretName: ''
caPath: /usr/local/share/ca-certificates
caKey: ca.crt

image:
  repository: dem-heights
  tag: v1.0.2

authentication:
    opa:
      enabled: false
      customHeaderName: ''

env:
  port: 80
  internalPort: 80
  targetPort: 8080
  protocol: TCP
  logLevel: info
  logPrettyPrintEnabled: false
  responseCompressionEnabled: true
  requestPayloadLimit: 1mb
  tracing:
    enabled: false
    url: http://localhost:55681/v1/trace
  metrics:
    enabled: false
    url: http://localhost:55681/v1/metrics
  terrainProvidersToken: ''
  demCatalogRecords: []
  protoFileUrl: ''
  serviceVersion: ''
  maximumTilesPerRequest: 150

opa:
  image: openpolicyagent/opa
  imageTag: 0.29.4-envoy-3
  port: 9191
  enableLogging: false
  resources:
    enabled: true
    value:
      limits:
        cpu: 400m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 200Mi
        
envoy:
  image: envoyproxy/envoy
  imageTag: v1.20.7
  port: 8000
  maxRequestBytes: 8192
  requestedDomain: rasterExport
  resources:
    enabled: true
    value:
      limits:
        cpu: 400m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 200Mi

resources:
  enabled: true
  value:
    limits:
      cpu: 1000m
      memory: 200Mi
    requests:
      cpu: 250m
      memory: 200Mi

route:
  enabled: true
  https: true
  host:
  path: /api/heights/v1
  timeout:
    enabled: false # defaults to 30s by openshift
    duration: 60s # supported units (us, ms, s, m, h, d)
  useCert: false

ingress:
  enabled: false
  type: nginx-org # supported values: 'nginx-org' | 'nginx-kubernetes
  tls:
    enabled: false
    useExternal: ''
  host:
  path: /api/heights/v1
  cors:
    enabled: true
    origin: '*'
